---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd # Argo CD가 설치된 네임스페이스
spec:
  project: default # 기본 프로젝트
  source:
    repoURL: https://github.com/jyje/pilot-gitops-argocd.git
    targetRevision: main
    path: clusters/jyje-step2/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Argo CD가 설치된 네임스페이스
  syncPolicy:
    automated: {}
---
# 프로젝트를 별도로 선언할 수 있습니다. 추가 프로젝트를 사용하지 않을 경우 생략합니다.
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system # 새로 만든 프로젝트 입니다
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'
